# Generated by Django 5.2.4 on 2025-12-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CASHIER', 'Caissier'), ('ACCOUNTANT', 'Comptable')], default='ADMIN', max_length=20),
        ),
    ]
