# Generated by Django 5.2.4 on 2025-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FREE', 'Gratuit'), ('MEDIUM', 'Medium'), ('PRO', 'Pro')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('features', models.TextField(help_text='Une fonctionnalité par ligne')),
                ('is_popular', models.BooleanField(default=False)),
                ('whatsapp_number', models.CharField(default='22500000000', max_length=20)),
            ],
        ),
    ]
