# Generated by Django 5.2.4 on 2025-12-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Gratuit'), ('MEDIUM', 'Medium'), ('PRO', 'Pro'), ('PRO_PLUS', 'Pro+')], default='FREE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('FREE', 'Gratuit'), ('MEDIUM', 'Medium'), ('PRO', 'Pro'), ('PRO_PLUS', 'Pro+')], max_length=20, unique=True),
        ),
    ]
