# Generated by Django 5.2.4 on 2025-12-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_customer_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('LOAN', 'Prêt (Client doit)'), ('DEBT', 'Dette (Boutique doit)')], default='LOAN', max_length=10),
        ),
    ]
