# Generated by Django 5.2.4 on 2025-12-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('MOMO', 'Mobile Money'), ('BANK', 'Virement Bancaire'), ('CARD', 'Carte Bancaire')], default='CASH', max_length=10),
        ),
    ]
